name: Ampliance Import
on:
  workflow_dispatch:
    inputs:
      content_item:
        description: "Content items to import"
        required: true
        default: all
        type: choice
        options:
          - all
          - content-type-schemas
          - content-types
          - extensions
      environment:
        description: "Target environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Import to Ampliance Hub
        run: |
          echo "Running import of \"${{ github.event.inputs.content_item }}\" to ${{ github.event.inputs.environment }} environment."
          
          ITEM="${{ github.event.inputs.content_item }}"

          echo "Variable is: ${VAR}"
          echo "Password is: $PASS}"
          
          case "$ITEM" in
            all)
              echo "content/content-type-schemas"
              echo "content/content-types"
              echo "extensions"
              ;;
              
            content-type-schemas|content-types)
              echo "content/$ITEM"
              ;;
              
            extensions)
              echo "$ITEM"
              ;;
          esac
