name: Ampliance Import
on:
  workflow_dispatch:
    inputs:
      content_item:
        description: "Items to import"
        required: true
        default: all
        type: choice
        options:
          - all
          - content-type-schemas
          - content-types
          - extensions
      environment:
        description: "Target environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - acc
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:trixie
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Import to Ampliance Hub
        run: |
          set -e

          echo "Running import of \"${{ github.event.inputs.content_item }}\" to ${{ github.event.inputs.environment }} environment."

          npm install -g @amplience/dc-cli
          echo $PATH
          export PATH="$(npm config get prefix)/bin:$PATH"
          echo $PATH
          export PATH="/usr/local/bin:$PATH"
          echo $PATH

          ITEM="${{ github.event.inputs.content_item }}"

          CLI_ARGS="--hubId ${HUB_ID} --clientId ${CLIENT_ID} --clientSecret ${CLIENT_SECRET}"

          run_import () {
            local TYPE=$1
            local PATH=$2

            echo "Importing ${TYPE}"
            dc-cli "${TYPE}" import "${PATH}" ${CLI_ARGS}
          }

          case "${ITEM}" in
            all)
              run_import "content-type-schema" "./content/content-type-schemas"
              run_import "content-type" "./content/content-types"
              run_import "extension" "./extensions"
              ;;

            content-type-schemas)
              run_import "content-type-schema" "./content/${ITEM}"
              ;;

            content-types)
              run_import "content-type" "./content/${ITEM}"
              ;;

            extensions)
              run_import "extension" "./${ITEM}"
              ;;

            *)
              echo "Invalid input: ${ITEM}. Nothing imported."
              exit 1
              ;;
          esac
